import { Router } from 'express';
import authRoutes from './auth.routes';
import auditRoutes from './audit.routes';
import dashboardRoutes from './dashboard.routes';
import vendorRoutes from './vendor.routes';
import quotationRoutes from './quotation.routes';
import workTaskRoutes from './work-task.routes';
import purchaseOrderRoutes from './purchase-order.routes';
import invoiceRoutes from './invoice.routes';
import paymentRoutes from './payment.routes';
import paymentSheetRoutes from './payment-sheet.routes';
import gatePassRoutes from './gate-pass.routes';
import goodsReceiptRoutes from './goods-receipt.routes';
import gstRecordRoutes from './gst-record.routes';
import inventoryRoutes from './inventory.routes';
import stockEntryRoutes from './stock-entry.routes';
import assetRoutes from './asset.routes';
import phaseRoutes from './phase.routes';
import activityRoutes from './activity.routes';
import photoRoutes from './photo.routes';
import issueRoutes from './issue.routes';
import inspectionRoutes from './inspection.routes';
import documentRoutes from './document.routes';
import documentLibraryRoutes from './document-library.routes';
import contractRoutes from './contract.routes';
import labourRoutes from './labour.routes';
import dropdownOptionRoutes from './dropdown-option.routes';
import attachmentRoutes from './attachment.routes';
import relatedRecordsRoutes from './related-records.routes';
import settingsRoutes from './settings.routes';
import ocrRoutes from './ocr.routes';
import notificationRoutes from './notification.routes';
import budgetHeadRoutes from './budget-heads.routes';
import bankAccountRoutes from './bank-accounts.routes';
import cashAccountRoutes from './cash-accounts.routes';
import ownerAccountRoutes from './owner-account.routes';
import financeReportRoutes from './finance-reports.routes';
import budgetRevisionRoutes from './budget-revisions.routes';
import ledgerRoutes from './ledger.routes';
import voucherRoutes from './voucher.routes';
import accountingReportRoutes from './accounting-reports.routes';
import paymentReportRoutes from './payment-reports.routes';
import mprRoutes from './mpr.routes';
import transactionRegisterRoutes from './transaction-register.routes';
import commentRoutes from './comment.routes';
import activityLogRoutes from './activity-log.routes';
import projectRoutes from './project.routes';
import searchRoutes from './search.routes';
import assistantRoutes from './assistant.routes';
import chatRoutes from './chat.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/projects', projectRoutes);
router.use('/audit', auditRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/vendors', vendorRoutes);
router.use('/quotations', quotationRoutes);
router.use('/work-tasks', workTaskRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/payment-sheets', paymentSheetRoutes);
router.use('/gate-passes', gatePassRoutes);
router.use('/goods-receipts', goodsReceiptRoutes);
router.use('/gst-records', gstRecordRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/stock-entries', stockEntryRoutes);
router.use('/assets', assetRoutes);
router.use('/phases', phaseRoutes);
router.use('/activities', activityRoutes);
router.use('/photos', photoRoutes);
router.use('/issues', issueRoutes);
router.use('/inspections', inspectionRoutes);
router.use('/documents', documentRoutes);
router.use('/document-library', documentLibraryRoutes);
router.use('/contracts', contractRoutes);
router.use('/labour', labourRoutes);
router.use('/dropdown-options', dropdownOptionRoutes);
router.use('/attachments', attachmentRoutes);
router.use('/related-records', relatedRecordsRoutes);
router.use('/settings', settingsRoutes);
router.use('/ocr', ocrRoutes);
router.use('/notifications', notificationRoutes);
router.use('/budget-heads', budgetHeadRoutes);
router.use('/bank-accounts', bankAccountRoutes);
router.use('/cash-accounts', cashAccountRoutes);
router.use('/owner-accounts', ownerAccountRoutes);
router.use('/finance-reports', financeReportRoutes);
router.use('/budget-revisions', budgetRevisionRoutes);
router.use('/ledgers', ledgerRoutes);
router.use('/vouchers', voucherRoutes);
router.use('/accounting-reports', accountingReportRoutes);
router.use('/payment-reports', paymentReportRoutes);
router.use('/material-purchase-requests', mprRoutes);
router.use('/transaction-register', transactionRegisterRoutes);
router.use('/comments', commentRoutes);
router.use('/activity-log', activityLogRoutes);
router.use('/search', searchRoutes);
router.use('/assistant', assistantRoutes);
router.use('/chat', chatRoutes);

export default router;
