import { Router } from 'express';
import authRoutes from './auth.routes';
import auditRoutes from './audit.routes';
import dashboardRoutes from './dashboard.routes';
import vendorRoutes from './vendor.routes';
import quotationRoutes from './quotation.routes';
import workTaskRoutes from './work-task.routes';
import purchaseOrderRoutes from './purchase-order.routes';
import invoiceRoutes from './invoice.routes';
import paymentRoutes from './payment.routes';
import gatePassRoutes from './gate-pass.routes';
import goodsReceiptRoutes from './goods-receipt.routes';
import gstRecordRoutes from './gst-record.routes';
import inventoryRoutes from './inventory.routes';
import assetRoutes from './asset.routes';
import phaseRoutes from './phase.routes';
import activityRoutes from './activity.routes';
import photoRoutes from './photo.routes';
import issueRoutes from './issue.routes';
import inspectionRoutes from './inspection.routes';
import documentRoutes from './document.routes';
import contractRoutes from './contract.routes';
import labourRoutes from './labour.routes';
import dropdownOptionRoutes from './dropdown-option.routes';
import attachmentRoutes from './attachment.routes';
import settingsRoutes from './settings.routes';
import ocrRoutes from './ocr.routes';
import notificationRoutes from './notification.routes';
import budgetHeadRoutes from './budget-heads.routes';
import bankAccountRoutes from './bank-accounts.routes';
import cashAccountRoutes from './cash-accounts.routes';
import ownerAccountRoutes from './owner-account.routes';
import journalVoucherRoutes from './journal-vouchers.routes';
import financeReportRoutes from './finance-reports.routes';
import budgetRevisionRoutes from './budget-revisions.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/audit', auditRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/vendors', vendorRoutes);
router.use('/quotations', quotationRoutes);
router.use('/work-tasks', workTaskRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/gate-passes', gatePassRoutes);
router.use('/goods-receipts', goodsReceiptRoutes);
router.use('/gst-records', gstRecordRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/assets', assetRoutes);
router.use('/phases', phaseRoutes);
router.use('/activities', activityRoutes);
router.use('/photos', photoRoutes);
router.use('/issues', issueRoutes);
router.use('/inspections', inspectionRoutes);
router.use('/documents', documentRoutes);
router.use('/contracts', contractRoutes);
router.use('/labour', labourRoutes);
router.use('/dropdown-options', dropdownOptionRoutes);
router.use('/attachments', attachmentRoutes);
router.use('/settings', settingsRoutes);
router.use('/ocr', ocrRoutes);
router.use('/notifications', notificationRoutes);
router.use('/budget-heads', budgetHeadRoutes);
router.use('/bank-accounts', bankAccountRoutes);
router.use('/cash-accounts', cashAccountRoutes);
router.use('/owner-accounts', ownerAccountRoutes);
router.use('/journal-vouchers', journalVoucherRoutes);
router.use('/finance-reports', financeReportRoutes);
router.use('/budget-revisions', budgetRevisionRoutes);

export default router;
