import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './enumOptions';

interface InvoiceItem {
  description?: string;
  quantity?: number;
  unit?: string;
  rate?: number;
  amount?: number;
  gstRate?: number;
  gstAmount?: number;
}

interface InvoicePDFData {
  invoiceCode: string;
  invoiceNumber: string;
  invoiceDate: string;
  vendorName: string;
  vendorCode?: string;
  vendorGst?: string;
  vendorAddress?: string;
  vendorPhone?: string;
  subtotal: number;
  cgst?: number;
  sgst?: number;
  igst?: number;
  totalGst: number;
  grandTotal: number;
  items: InvoiceItem[];
  projectName?: string;
  notes?: string;
}

export function generateInvoicePDF(data: InvoicePDFData) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 15;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', pageWidth / 2, y, { align: 'center' });
  y += 6;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(data.projectName ?? 'Hospital Construction ERP', pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Invoice details (left) and vendor details (right)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Invoice Details', 15, y);
  doc.text('Vendor Details', pageWidth - 15, y, { align: 'right' });
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const leftCol = [
    `Invoice Code: ${data.invoiceCode}`,
    `Invoice No: ${data.invoiceNumber}`,
    `Date: ${formatDate(data.invoiceDate)}`,
  ];
  const rightCol = [
    data.vendorName,
    data.vendorCode && `Code: ${data.vendorCode}`,
    data.vendorGst && `GST: ${data.vendorGst}`,
    data.vendorPhone && `Phone: ${data.vendorPhone}`,
  ].filter(Boolean) as string[];

  leftCol.forEach((line, i) => doc.text(line, 15, y + i * 4.5));
  rightCol.forEach((line, i) => doc.text(line, pageWidth - 15, y + i * 4.5, { align: 'right' }));
  y += Math.max(leftCol.length, rightCol.length) * 4.5 + 5;

  if (data.vendorAddress) {
    doc.text(data.vendorAddress, pageWidth - 15, y, { align: 'right' });
    y += 5;
  }

  // Items table
  autoTable(doc, {
    head: [['#', 'Description', 'Qty', 'Unit', 'Rate', 'Amount', 'GST %', 'GST Amt']],
    body: data.items.map((item, idx) => [
      String(idx + 1),
      item.description ?? '—',
      String(item.quantity ?? 0),
      item.unit ?? '',
      formatCurrency(item.rate ?? 0),
      formatCurrency(item.amount ?? 0),
      `${item.gstRate ?? 0}%`,
      formatCurrency(item.gstAmount ?? 0),
    ]),
    startY: y,
    theme: 'striped',
    headStyles: { fillColor: [130, 177, 255], fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 55 } },
  });

  // @ts-expect-error — autoTable adds lastAutoTable to doc
  y = doc.lastAutoTable.finalY + 8;

  // Totals
  const totalsX = pageWidth - 80;
  doc.setFontSize(9);
  const totals: [string, string][] = [
    ['Subtotal', formatCurrency(data.subtotal)],
    ...(data.cgst ? [['CGST', formatCurrency(data.cgst)]] as [string, string][] : []),
    ...(data.sgst ? [['SGST', formatCurrency(data.sgst)]] as [string, string][] : []),
    ...(data.igst ? [['IGST', formatCurrency(data.igst)]] as [string, string][] : []),
    ['Total GST', formatCurrency(data.totalGst)],
  ];
  totals.forEach(([label, val]) => {
    doc.text(label, totalsX, y);
    doc.text(val, pageWidth - 15, y, { align: 'right' });
    y += 5;
  });

  // Grand total
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(130, 177, 255);
  doc.rect(totalsX - 2, y - 4, pageWidth - totalsX - 13, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.text('Grand Total', totalsX, y);
  doc.text(formatCurrency(data.grandTotal), pageWidth - 15, y, { align: 'right' });
  doc.setTextColor(0, 0, 0);
  y += 12;

  // Notes
  if (data.notes) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(`Notes: ${data.notes}`, 15, y);
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Hospital Construction ERP', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  doc.save(`Invoice-${data.invoiceCode || data.invoiceNumber}.pdf`);
}
